import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Nav from "./components/Nav";
import Socials from "./components/Socials";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Home | MB",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`h-screen w-screen flex flex-col text-center items-center justify-center overflow-hidden ${inter.className} gap-12`}>
                <header>
                    <Nav />
                </header>
                {children}
                <footer>
                    <Socials />
                </footer>
            </body>
        </html>
    );
}
